### PR TITLE
Update deps, migrate to gen2 cloud function🌲

### PR DESCRIPTION
**Pull request by jacobdadams**
We'll also need to remove the existing wmrc-skid function in the prod environment before this can deploy to prod.

### CODE REVIEW

**Comment by steveoh** [comment]
Do you want me to delete the existing so you don't have to rename it?

**Comment by jacobdadams** [comment]
yes please.

**Comment by steveoh** [comment]
Ok, after you update that and I delete the existing one I will merge this. I delete them in dev and prod.

**Comment by jacobdadams** [comment]
I thought i had... (I undid the name change in the last big commit)

**Review by steveoh — APPROVED** [review]

**Pull request merged**
